title: Pir치ti T치bor
default_locale: "cs"
permalink: pretty
markdown: kramdown
facebookurl: https://www.facebook.com/piratitabor
logo: /static/logo.png

keywords: t치bor,pir치ti
url: https://tabor.pirati.cz
